[changelog]
header = "# Changelog\n"
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
trim = true
render_always = true
postprocessors = []

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
commit_preprocessors = [
    { pattern = ":arrow_up:", replace = "chore(deps):" },
    { pattern = ":bookmark:", replace = "chore(release):" },
    { pattern = ":bug:", replace = "fix:" },
    { pattern = ":rocket:", replace = "chore:" },
    { pattern = ":sparkles:", replace = "feat:" },
    { pattern = ":memo:", replace = "docs:" },
    { pattern = ":white_check_mark:", replace = "test:" },
    { pattern = ":recycle:", replace = "refactor:" },
    { pattern = ":zap:", replace = "perf:" },
    { pattern = ":wrench:", replace = "chore:" },
    { pattern = ":construction_worker:", replace = "ci:" },
    { pattern = ":rewind:", replace = "revert:" },
    { pattern = ":fire:", replace = "chore:" },
    { pattern = ":green_heart:", replace = "ci:" },
    { pattern = ":lock:", replace = "fix:" },
    { pattern = ":ambulance:", replace = "hotfix:" },
    { pattern = "✨ ", replace = "feat: " },
    { pattern = "🐛 ", replace = "fix: " },
    { pattern = "📝 ", replace = "docs: " },
    { pattern = "♻️ ", replace = "refactor: " },
    { pattern = "⚡ ", replace = "perf: " },
    { pattern = "✅ ", replace = "test: " },
    { pattern = "🔧 ", replace = "chore: " },
    { pattern = "👷 ", replace = "ci: " },
    { pattern = "⏪️ ", replace = "revert: " },
    { pattern = "⬆️ ", replace = "chore(deps): " },
    { pattern = "💥 ", replace = "feat!: " },
    { pattern = "🚀 ", replace = "chore: " },
    { pattern = "💚 ", replace = "ci: " },
    { pattern = "🔒️ ", replace = "fix: " },
    { pattern = "🚑️ ", replace = "hotfix: " },
    { pattern = "💄 ", replace = "style: " },
    { pattern = "🔥 ", replace = "chore: " },
]
protect_breaking_commits = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^hotfix", group = "Bug Fixes" },
    { message = "^doc", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps\\)", group = "Dependencies" },
    { message = "^chore|^ci", group = "Miscellaneous Tasks" },
    { message = "^revert", group = "Revert" },
    { message = ".*", group = "Other" },
]
filter_commits = false
fail_on_unmatched_commit = false
link_parsers = []
use_branch_tags = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
recurse_submodules = false